### ISSUE TITLE
Text format / CSS not used when switching to "New look" in D365

### ISSUE THREAD

**Issue by orb-mue-mar** [DigitalFlow/Xrm-Templating-Language#63]
Hi Florian,

we can reproduce a problem with the formatting when switching to the "new look" in D365.
It seems that the CSS within the HTML isnt used at all. We already updated it to the latest release.

"New look" turned off:
![image](https://github.com/XRM-OSS/Xrm-Templating-Language/assets/167413684/a4ba2079-1b7c-4b2f-9d14-106b0d14c346)

"New look" tuned on: (it also seems that another Editor is in use then, but i am not sure about that)
![image](https://github.com/XRM-OSS/Xrm-Templating-Language/assets/167413684/a5e81f01-3d7d-4450-b7aa-c729762a9fa9)

Thank you to have look into it in advance!
Marcus

**Comment by DigitalFlow** [comment]
Hi Marcus,

this seems to be about the display of the templated data inside the dynamics rich text editor rather than about the designer itself, right?
I'll take a look at it. Might be though that it's Microsoft that is interfering with the CSS classes in the new UI.

Kind regards,
Florian

**Comment by orb-mue-mar** [comment]
> Hi Marcus,
> 
> this seems to be about the display of the templated data inside the dynamics rich text editor rather than about the designer itself, right? I'll take a look at it. Might be though that it's Microsoft that is interfering with the CSS classes in the new UI.
> 
> Kind regards, Florian

Yes, the problem seems to be within the rich text editor when switching to "New look". Thanks for having a look into it.

Regards,
Marcus

**Comment by catalinpotinte** [comment]
Hi Florian, 

I can confirm we have the same issue in our tenant with the templates when switching to the New look.

Thank you for taking a look.

Best Regards, 
Catalin

**Comment by orb-mue-mar** [comment]
Could you find the find to have a look into it?

Kind regards,
Marcus

**Comment by catalinpotinte** [comment]
Update:

The above issues still persist with activating the new look.

Lately there is a new "development" and with the new look randomly the body of email fails to load
![image](https://github.com/user-attachments/assets/3113ec69-1083-4a80-9da8-ebb7ef26749a)

The error message is:

Error Details: Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at bu (https://content.powerapps.com/resource/uci-infra-bus/scripts/vendor.1cae5aa28fca3d26e5e989792f80fda6.js:9:89469)
    at Nl (https://content.powerapps.com/resource/uci-infra-bus/scripts/vendor.1cae5aa28fca3d26e5e989792f80fda6.js:9:101256)
    at t.unstable_runWithPriority (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.1770bc40965b9d51aafd016172077d13.js:14:3768)
    at Wo (https://content.powerapps.com/resource/uci-infra-bus/scripts/vendor.1cae5aa28fca3d26e5e989792f80fda6.js:9:44549)
    at Tl (https://content.powerapps.com/resource/uci-infra-bus/scripts/vendor.1cae5aa28fca3d26e5e989792f80fda6.js:9:99217)
    at pl (https://content.powerapps.com/resource/uci-infra-bus/scripts/vendor.1cae5aa28fca3d26e5e989792f80fda6.js:9:95328)
    at https://content.powerapps.com/resource/uci-infra-bus/scripts/vendor.1cae5aa28fca3d26e5e989792f80fda6.js:9:44772
    at t.unstable_runWithPriority (https://content.powerapps.com/resource/uci-infra-bus/scripts/app.1770bc40965b9d51aafd016172077d13.js:14:3768)
    at Wo (https://content.powerapps.com/resource/uci-infra-bus/scripts/vendor.1cae5aa28fca3d26e5e989792f80fda6.js:9:44549)
    at Qo (https://content.powerapps.com/resource/uci-infra-bus/scripts/vendor.1cae5aa28fca3d26e5e989792f80fda6.js:9:44717)

Did anyone else encounter this?

Thank you in advance for your help.

**Comment by DigitalFlow** [comment]
I set up an organization where I can try the "new look" and report my findings.
The issue you posted looks very much like the platform was doing something that breaks it.
